version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: YourStrong@Pass123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"